import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { GlobalContextProvider } from '@/context/BoredApiContext'
import TitleAndForm from '@/components/TitleAndForm'
import Image from 'next/image'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Bored API',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <GlobalContextProvider>
          <TitleAndForm />
          {children}
          <div className='absolute right-10 flex items-end'>
            <h5 className='text-gray-500 font-light mb-2 me-4 italic'>
              Built by Philcob Suzuki Josol
            </h5>
            <Image
              className='w-36'
              src='/bored-illustration.png'
              alt=''
              width={500}
              height={500}
            />
          </div>
        </GlobalContextProvider>
      </body>
    </html>
  )
}
